import { ArrowLeft, CheckCircle2, MapPin, MessageCircle, Truck } from 'lucide-react'
import type { FormEvent } from 'react'
import { Header } from '../components/Header'
import { cartDetails, clearCart } from '../lib/cart'

export function CheckoutPage() {
  const lines = cartDetails()
  const subtotal = lines.reduce((sum,line)=>sum+line.product.price*line.quantity,0)
  const money = (n:number)=>new Intl.NumberFormat('en-UG').format(n)
  const submit = (e:FormEvent) => { e.preventDefault(); clearCart(); window.location.href='/order/GLK-2420' }
  return <div className="app-shell"><Header/><main className="page-container checkout-page"><a className="back-link" href="/cart"><ArrowLeft size={17}/> Back to cart</a><div className="checkout-heading"><span className="section-kicker">Guest checkout</span><h1>Almost yours.</h1><p>No account needed.</p></div><form className="checkout-grid" onSubmit={submit}><section className="checkout-form-card"><h2>Contact</h2><div className="form-grid"><label><span>Full name</span><input required placeholder="Your name"/></label><label><span>Phone / WhatsApp</span><input required placeholder="+256..."/></label><label className="wide"><span>Email <small>optional</small></span><input type="email" placeholder="you@example.com"/></label></div><h2>Delivery</h2><div className="delivery-options"><label><input type="radio" name="delivery" defaultChecked/><span><Truck size={19}/><div><strong>Delivery</strong><small>Seller confirms fee and timing.</small></div></span></label><label><input type="radio" name="delivery"/><span><MapPin size={19}/><div><strong>Pickup</strong><small>Collect directly from the shop.</small></div></span></label></div><label className="stack-label"><span>Delivery location</span><textarea required placeholder="Area, landmark or directions"/></label><label className="stack-label"><span>Order note <small>optional</small></span><textarea placeholder="Anything the seller should know?"/></label></section><aside className="checkout-summary"><h2>Order</h2>{lines.length?lines.map(line=><div className="checkout-line" key={line.productId}><img src={line.product.image} alt=""/><div><strong>{line.product.name}</strong><small>Qty {line.quantity}</small></div><span>UGX {money(line.product.price*line.quantity)}</span></div>):<p className="muted">Your cart is empty. The demo checkout can still be previewed.</p>}<div className="checkout-total"><span>Total</span><strong>UGX {money(subtotal)}</strong></div><button className="primary-button large full-width"><CheckCircle2 size={18}/> Place order</button><a className="whatsapp-checkout" href="https://wa.me/256700000000" target="_blank" rel="noreferrer"><MessageCircle size={17}/> Prefer WhatsApp? Chat with seller</a></aside></form></main></div>
}
