import { ArrowUpRight, BarChart3, Boxes, Eye, MessageCircle, MoreHorizontal, PackagePlus, Plus, Search, Settings2, ShoppingBag, TrendingUp, Users } from 'lucide-react'
import { DashboardShell } from '../components/DashboardShell'
import { customers, orders, products } from '../data/mock'

const money=(n:number)=>new Intl.NumberFormat('en-UG').format(n)
const ActionButton=({label='Add product'}:{label?:string})=><a className="primary-button" href="/dashboard/products"><Plus size={17}/>{label}</a>

export function DashboardHomePage(){return <DashboardShell title="Overview" subtitle="Here’s what’s happening with your shop." action={<ActionButton/>}><section className="metric-grid"><article><span className="metric-icon"><ShoppingBag size={20}/></span><div><small>Orders</small><strong>24</strong><em>+12% this week</em></div></article><article><span className="metric-icon"><TrendingUp size={20}/></span><div><small>Sales</small><strong>UGX 1.84M</strong><em>+18% this week</em></div></article><article><span className="metric-icon"><Eye size={20}/></span><div><small>Shop views</small><strong>1,284</strong><em>+9% this week</em></div></article><article><span className="metric-icon"><Users size={20}/></span><div><small>Customers</small><strong>86</strong><em>+7 new</em></div></article></section><div className="dashboard-two-col"><section className="dash-card"><div className="dash-card-head"><div><h2>Recent orders</h2><p>Latest activity from your shop.</p></div><a href="/dashboard/orders">View all</a></div><div className="order-table">{orders.map(o=><div className="order-row" key={o.id}><div><strong>{o.id}</strong><small>{o.customer}</small></div><span>UGX {money(o.total)}</span><span className={`status-pill ${o.status.toLowerCase()}`}>{o.status}</span><small>{o.time}</small></div>)}</div></section><aside className="dash-card shop-performance"><div className="dash-card-head"><div><h2>Store health</h2><p>Quick actions.</p></div></div><div className="health-score"><strong>82</strong><span>/100</span></div><div className="health-item"><span>Complete business profile</span><b>Done</b></div><div className="health-item"><span>Add 5 more products</span><b>+8 pts</b></div><div className="health-item"><span>Add delivery info</span><b>+5 pts</b></div><a className="soft-button full-width" href="/dashboard/store"><Settings2 size={17}/> Improve store</a></aside></div></DashboardShell>}

export function DashboardProductsPage(){return <DashboardShell title="Products" subtitle="Manage what customers see in your shop." action={<ActionButton/>}><section className="dash-card"><div className="product-toolbar"><label className="dashboard-search"><Search size={17}/><input placeholder="Search products"/></label><span>4 / 20 active on Free</span></div><div className="inventory-grid">{products.filter(p=>p.shopSlug==='nile-ai-solutions').map(p=><article className="inventory-card" key={p.id}><img src={p.image} alt={p.name}/><div className="inventory-body"><div><small>{p.category}</small><strong>{p.name}</strong></div><button><MoreHorizontal size={18}/></button><span>UGX {money(p.price)}</span><em>{p.stock} in stock</em></div></article>)}<button className="add-product-card"><PackagePlus size={26}/><strong>Add product</strong><span>16 slots left on Free</span></button></div></section></DashboardShell>}

export function DashboardOrdersPage(){return <DashboardShell title="Orders" subtitle="Track and manage customer orders."><section className="dash-card"><div className="dashboard-tabs"><button className="active">All <span>24</span></button><button>New <span>3</span></button><button>Confirmed</button><button>Delivering</button><button>Completed</button></div><div className="order-table roomy">{orders.concat(orders).map((o,i)=><div className="order-row" key={`${o.id}-${i}`}><div><strong>{o.id}</strong><small>{o.customer}</small></div><span>UGX {money(o.total)}</span><span className={`status-pill ${o.status.toLowerCase()}`}>{o.status}</span><small>{o.time}</small><button className="table-action"><ArrowUpRight size={16}/></button></div>)}</div></section></DashboardShell>}

export function DashboardCustomersPage(){return <DashboardShell title="Customers" subtitle="People who have ordered from your shop."><section className="dash-card"><div className="product-toolbar"><label className="dashboard-search"><Search size={17}/><input placeholder="Search customers"/></label><span>86 customers</span></div><div className="customer-list">{customers.map(c=><div className="customer-row" key={c.name}><span className="customer-avatar">{c.name[0]}</span><div><strong>{c.name}</strong><small>Last order: {c.last}</small></div><span>{c.orders} orders</span><strong>UGX {money(c.spent)}</strong><button className="table-action"><MessageCircle size={16}/></button></div>)}</div></section></DashboardShell>}

export function DashboardAnalyticsPage(){return <DashboardShell title="Analytics" subtitle="Understand what’s working."><section className="metric-grid"><article><span className="metric-icon"><BarChart3 size={20}/></span><div><small>Conversion</small><strong>3.8%</strong><em>+0.6%</em></div></article><article><span className="metric-icon"><Eye size={20}/></span><div><small>Views</small><strong>4,930</strong><em>30 days</em></div></article><article><span className="metric-icon"><ShoppingBag size={20}/></span><div><small>Orders</small><strong>67</strong><em>30 days</em></div></article><article><span className="metric-icon"><TrendingUp size={20}/></span><div><small>Revenue</small><strong>UGX 5.2M</strong><em>30 days</em></div></article></section><section className="dash-card analytics-card"><div className="dash-card-head"><div><h2>Sales trend</h2><p>Last 7 days</p></div></div><div className="fake-chart">{[36,58,48,72,62,88,76].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></section></DashboardShell>}

export function DashboardStorePage(){return <DashboardShell title="Store" subtitle="Customize how your business appears to customers." action={<a className="soft-button" href="/shop/nile-ai-solutions"><Eye size={17}/> Preview shop</a>}><div className="dashboard-two-col"><section className="dash-card form-card"><h2>Store profile</h2><div className="form-grid"><label className="wide"><span>Business name</span><input defaultValue="Nile AI Solutions"/></label><label><span>Category</span><input defaultValue="Tech & gadgets"/></label><label><span>Location</span><input defaultValue="Ntinda, Kampala"/></label><label className="wide"><span>Description</span><textarea defaultValue="Everyday tech. Exceptional possibilities."/></label><label className="wide"><span>WhatsApp</span><input defaultValue="+256 700 000 000"/></label><label className="wide"><span>Google Maps / Plus Code</span><input placeholder="Paste link or code"/></label><label><span>TikTok</span><input placeholder="@nileai"/></label><label><span>Instagram</span><input placeholder="@nileai"/></label></div><button className="primary-button">Save changes</button></section><aside className="dash-card"><h2>Brand style</h2><p className="muted">Gulako stays recognizable while your shop gets its own accent.</p><div className="accent-picker"><button className="accent violet active"/><button className="accent indigo"/><button className="accent rose"/><button className="accent amber"/><button className="accent teal"/></div><h3>Shop cover</h3><button className="upload-box"><Plus size={22}/><span>Add cover image</span></button></aside></div></DashboardShell>}

export function DashboardSettingsPage(){return <DashboardShell title="Settings" subtitle="Account, plan and business preferences."><div className="settings-stack"><section className="dash-card settings-row"><div><h2>Plan</h2><p>Free · 4 of 20 products active</p></div><a className="primary-button" href="/pricing">Upgrade</a></section><section className="dash-card settings-row"><div><h2>Login & security</h2><p>Email, Google, TikTok and phone sign-in.</p></div><button className="soft-button">Manage</button></section><section className="dash-card settings-row"><div><h2>Notifications</h2><p>Order alerts and business updates.</p></div><button className="soft-button">Configure</button></section><section className="dash-card danger-zone"><div><h2>Shop status</h2><p>Temporarily hide your shop from customers.</p></div><button className="soft-button">Pause shop</button></section></div></DashboardShell>}
